version: "3.7"
services:
  postgres_fruit_reactive:
    container_name: postgres_fruit_reactive
    image: postgres:12.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"